#!/bin/sh

### BEGIN INIT INFO
# Provides:        god
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start God daemon
### END INIT INFO  framework written in Ruby.
#

CONF_FILE=/etc/god.conf
DAEMON=/usr/local/bin/god
PIDFILE=<%= @app_root %>/tmp/god.pid
LOGFILE=<%= @app_root %>/log/god.log
SCRIPTNAME=/etc/init.d/god
USER=<%= @webapp_user %>
DEBUG_OPTIONS="--log-level debug"
RETVAL=0

god_start() {
      start_cmd="$DAEMON -l $LOGFILE -P $PIDFILE $DEBUG_OPTIONS -c $CONF_FILE"
      echo $start_cmd
      sudo su - $USER -c "$start_cmd" || echo -en "god already running"
}

god_stop() {
      stop_cmd="$DAEMON terminate"
      echo $stop_cmd
      sudo su - $USER -c "$stop_cmd" || echo -en "god not running"
}

god_status() {
      status_cmd="$DAEMON status"
      sudo su - $USER -c "$status_cmd"
}

case "$1" in
    start)
      god_start
      RETVAL=$?
  ;;
    stop)
      god_stop
      RETVAL=$?
  ;;
    restart)
      god_stop
      god_start
      RETVAL=$?
  ;;
    status)
      god_status
      RETVAL=$?
  ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL