#!/bin/bash
#
# god       Startup script for god (<a href="http://god.rubyforge.org">http://god.rubyforge.org</a>)
#
# chkconfig: - 99 1
# description: God is an easy to configure, easy to extend monitoring \
#              framework written in Ruby.
#

CONF_FILE=/etc/god.conf
DAEMON=/usr/local/bin/god
PIDFILE=<%= @app_root %>/tmp/god.pid
LOGFILE=<%= @app_root %>/log/god.log
SCRIPTNAME=/etc/init.d/god
USER=<%= @webapp_user %>

DEBUG_OPTIONS="--log-level debug"
#DEBUG_OPTIONS=""

RETVAL=0

god_start() {
      start_cmd="$DAEMON -l $LOGFILE -P $PIDFILE $DEBUG_OPTIONS -c $CONF_FILE"
      echo $start_cmd
      sudo su - $USER -c "$start_cmd" || echo -en "god already running"
      RETVAL=$?
      return $RETVAL
}

god_stop() {
      stop_cmd="$DAEMON terminate"
      #stop_cmd="kill -QUIT `cat $PIDFILE`"
      echo $stop_cmd
      sudo su - $USER -c "$stop_cmd" || echo -en "god not running"
}

case "$1" in
    start)
      god_start
      RETVAL=$?
  ;;
    stop)
      god_stop
      RETVAL=$?
  ;;
    restart)
      god_stop
      god_start
      RETVAL=$?
  ;;
    status)
      sudo su - $USER -c "$DAEMON status"
      RETVAL=$?
  ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL